/**
 * 🔄 TODO:
 * If Prisma enum changes, update this enum accordingly
 * @see Prisma ServiceName enum (audit-log.prisma)
 * @see PushChannel PushChannel enum (src\common\lib\pusher\pusher.types.ts)
 */
export enum ServiceName {
  HOLIDAY = 'HOLIDAY',
  HOLIDAY_ACCOUNT = 'HOLIDAY_ACCOUNT',
  NIROPEKKHO_NEWS = 'NIROPEKKHO_NEWS',
  NIROPEKKHO_NEWS_ACCOUNT = 'NIROPEKKHO_NEWS_ACCOUNT',
  FLYGHOR_AUTH = 'FLYGHOR_AUTH',
  FLYGHOR_B2B = 'FLYGHOR_B2B',
  FLYGHOR_B2C = 'FLYGHOR_B2C',
  FLYGHOR_ADMIN = 'FLYGHOR_ADMIN',
  NARIA_TRAVEL_AND_TOUR = 'NARIA_TRAVEL_AND_TOUR',
  NARIA_TRAVEL_AND_TOUR_ACCOUNT = 'NARIA_TRAVEL_AND_TOUR_ACCOUNT',
  HASAN_OVERSEAS = 'HASAN_OVERSEAS',
  HASAN_OVERSEAS_ACCOUNT = 'HASAN_OVERSEAS_ACCOUNT',
  NARIA_IT_SOLUTIONS = 'NARIA_IT_SOLUTIONS',
  NARIA_IT_SOLUTIONS_ACCOUNT = 'NARIA_IT_SOLUTIONS_ACCOUNT',
  RAYHAN_ENTERPRISE = 'RAYHAN_ENTERPRISE',
  RAYHAN_ENTERPRISE_ACCOUNT = 'RAYHAN_ENTERPRISE_ACCOUNT',
  AUTOMATION = 'AUTOMATION',
}
