{
 "title": "Automation Service",
 "tags": [ "automation-service" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=~\"automation-api|automation-service-worker.*|automation-api-dev|automation-service-dev-worker.*|automation-maintenance|automation-maintenance-dev\"}"
    }
   ]
  },
  {
   "title": "Prometheus Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Scraped Process Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds"
    }
   ]
  }
 ]
}