-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "auth";

CREATE SCHEMA IF NOT EXISTS "automation";

CREATE SCHEMA IF NOT EXISTS "common";

CREATE SCHEMA IF NOT EXISTS "logs";

CREATE SCHEMA IF NOT EXISTS "media";